{
    'name': 'Stock Serial Upload (Serial Column Only)',
    'version': '1.0.0',
    'summary': 'Upload serial numbers (one-column Excel) to internal transfers',
    'description': 'Wizard to import serial numbers (single "serial" column) and create/attach lots and move lines on internal stock pickings.',
    'category': 'Inventory/Operations',
    'author': 'Generated by ChatGPT',
    'website': '',
    'depends': ['stock'],
    'data': [
        'security/ir.model.access.csv',
        'views/upload_serial_only_wizard_view.xml',
        'views/stock_picking_inherit_view.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
