import logging
from datetime import timedelta

from odoo import api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class StockPicking(models.Model):
    _inherit = 'stock.picking'

    # ─── Extra Fields added to stock.picking ──────────────────────────────────

    validation_status = fields.Selection(
        selection=[
            ('pending',   'Pending'),
            ('validated', 'Validated'),
            ('failed',    'Failed'),
        ],
        string='Validation Status',
        default='pending',
        copy=False,
        tracking=True,
        index=True,
    )

    validation_error = fields.Text(
        string='Validation Error',
        readonly=True,
        copy=False,
    )

    validated_at = fields.Datetime(
        string='Validated At',
        readonly=True,
        copy=False,
    )

    # ─── Duplicate Serial Number Fix ──────────────────────────────────────────
    # stock.picking already has a unique `name` generated by ir.sequence.
    # The real duplicate issue is in stock.lot (serial numbers on products).
    # We add a constraint + override to prevent duplicate lot/serial numbers
    # within the same picking.



    # ─── Validation Logic ─────────────────────────────────────────────────────

    def _run_validation_checks(self):
        """
        Business-logic validation for a single stock.picking.
        Returns (passed: bool, error_message: str).

        picking_type_code values:
            'outgoing'  → Delivery Order   (تسليم)
            'incoming'  → Receipt           (استلام)
            'internal'  → Internal Transfer
        """
        self.ensure_one()
        errors = []

        # ── Common checks (both delivery & receipt) ──────────────────────────
        if not self.move_ids:
            errors.append('لا توجد أصناف في العملية.')

        if self.state == 'cancel':
            errors.append('العملية ملغية.')

        # Check for duplicate serial numbers across all move lines
        # Check for duplicate serial numbers across all move lines
        serials = [
            ml.lot_id.name
            for ml in self.move_line_ids
            if ml.lot_id and ml.lot_id.name
        ]
        duplicates = {s for s in serials if serials.count(s) > 1}

        if duplicates:
            lines_to_unlink = self.move_line_ids.filtered(
                lambda ml: ml.lot_id and ml.lot_id.name in duplicates
            )
            # احتفظ بأول سطر لكل تسلسل، واحذف الباقي
            seen = set()
            lines_to_remove = self.env['stock.move.line']
            for ml in lines_to_unlink:
                if ml.lot_id.name in seen:
                    lines_to_remove |= ml
                else:
                    seen.add(ml.lot_id.name)
            lines_to_remove.unlink()

        # Check that all demand quantities are filled
        for line in self.move_ids:
            if line.product_uom_qty <= 0:
                errors.append(
                    'الكمية المطلوبة للصنف "%s" يجب أن تكون أكبر من صفر.'
                    % line.product_id.display_name
                )

        # ── Delivery-specific checks ──────────────────────────────────────────
        if self.picking_type_code == 'outgoing':
            if not self.partner_id:
                errors.append('لم يتم تحديد العميل (Partner) للتسليم.')

            if not self.scheduled_date:
                errors.append('لم يتم تحديد تاريخ مجدول للتسليم.')

        # ── Receipt-specific checks ───────────────────────────────────────────
        elif self.picking_type_code == 'incoming':
            if not self.partner_id:
                errors.append('لم يتم تحديد المورد (Partner) للاستلام.')

            if not self.origin:
                errors.append('حقل المصدر (Source Document) فارغ في الاستلام.')

        # ── Add your own business rules below ─────────────────────────────────
        # e.g.:
        # if self.picking_type_code == 'outgoing' and not self.carrier_id:
        #     errors.append('شركة الشحن غير محددة.')
        # ─────────────────────────────────────────────────────────────────────

        if errors:
            return False, '\n'.join(f'• {e}' for e in errors)
        return True, ''

    # ─── Cron Entry-Point ─────────────────────────────────────────────────────

    @api.model
    def action_auto_validate_pending_pickings(self):
        """
        Called by ir.cron every minute.

        Targets stock.picking records where:
          - picking_type_code IN ('outgoing', 'incoming')   → deliveries & receipts only
          - state IN ('draft', 'waiting', 'confirmed', 'assigned')  → not yet done/cancelled
          - validation_status = 'pending'
          - create_date <= now - 5 minutes
        """
        cutoff = fields.Datetime.now() - timedelta(minutes=5)

        pending_pickings = self.search([
            ('picking_type_code', 'in', ['outgoing', 'incoming']),
            ('state', 'in', ['draft', 'waiting', 'confirmed', 'assigned']),
            ('validation_status', '=', 'pending'),
            ('create_date', '<=', cutoff),
        ])

        if not pending_pickings:
            _logger.info('Auto-Validate Cron: No pending pickings found.')
            return

        _logger.info(
            'Auto-Validate Cron: Found %d picking(s) to validate.',
            len(pending_pickings),
        )

        for picking in pending_pickings:
            try:
                passed, error_msg = picking._run_validation_checks()
                now = fields.Datetime.now()

                if passed:
                    picking.write({
                        'validation_status': 'validated',
                        'validated_at':      now,
                        'validation_error':  False,
                    })
                    picking.message_post(
                        body='✅ تم التحقق تلقائياً بواسطة المهمة المجدولة.',
                        subtype_xmlid='mail.mt_note',
                    )
                    _logger.info(
                        'Picking %s [%s] → VALIDATED ✓',
                        picking.name, picking.picking_type_code,
                    )
                else:
                    picking.write({
                        'validation_status': 'failed',
                        'validation_error':  error_msg,
                    })
                    picking.message_post(
                        body=f'❌ فشل التحقق:\n{error_msg}',
                        subtype_xmlid='mail.mt_note',
                    )
                    _logger.warning(
                        'Picking %s [%s] → FAILED ✗ | %s',
                        picking.name, picking.picking_type_code, error_msg,
                    )

            except Exception:
                _logger.exception(
                    'Unexpected error during auto-validation of picking %s',
                    picking.name,
                )

    # ─── Manual Buttons ───────────────────────────────────────────────────────

    def action_manual_validate(self):
        """Button on form: manually trigger validation checks."""
        for picking in self:
            passed, error_msg = picking._run_validation_checks()
            if passed:
                picking.write({
                    'validation_status': 'validated',
                    'validated_at':      fields.Datetime.now(),
                    'validation_error':  False,
                })
                picking.message_post(
                    body='✅ تم التحقق يدوياً.',
                    subtype_xmlid='mail.mt_note',
                )
            else:
                raise UserError('فشل التحقق:\n\n%s' % error_msg)

    def action_reset_validation(self):
        """Reset validation status back to pending."""
        for picking in self:
            picking.write({
                'validation_status': 'pending',
                'validation_error':  False,
                'validated_at':      False,
            })
            picking.message_post(
                body='🔄 تم إعادة حالة التحقق إلى "قيد الانتظار".',
                subtype_xmlid='mail.mt_note',
            )
